services:

  # API gateway
  nginx:
    build: ./gateway
    ports:
      - "80:80"
    depends_on:
      - auth-service
      - client-service
      - invoice-service
      - payment-service
    networks:
      - invoicehive_net


  # frontend:
  #   build: ./client
  #   environment:
  #     - NEXT_PUBLIC_API_URL=http://localhost
  #   depends_on:
  #     - nginx
  #   networks:
  #     - invoicehive_net


  auth-service:
    build: ./auth-service
    environment:
      - PORT=3001
      - NODE_ENV=development

      # atlas + upstash
      - MONGO_URI=${MONGO_URI}
      - REDIS_URL=${REDIS_URL}

      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}

      - CLIENT_URL=http://localhost:3000

    networks:
      - invoicehive_net


  client-service:
    build: ./client-service
    environment:
      - PORT=3002
      - NODE_ENV=development

      - MONGO_URI=${MONGO_URI}

      
      - INTERNAL_SECRET=${INTERNAL_SECRET}

    networks:
      - invoicehive_net


  invoice-service:
    build: ./invoice-service
    environment:
      - PORT=3003

      - MONGO_URI=${MONGO_URI}

    

      - RABBITMQ_URL=amqp://rabbitmq:5672

      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET=invoicehive

      - INTERNAL_SECRET=${INTERNAL_SECRET}

      - CLIENT_SERVICE_URL=http://client-service:3002

    depends_on:
      - rabbitmq
      - minio

    networks:
      - invoicehive_net


  payment-service:
    build: ./payment-service
    environment:
      - PORT=3004

      - MONGO_URI=${MONGO_URI}

      - RAZORPAY_KEY_ID=${RAZORPAY_KEY_ID}
      - RAZORPAY_KEY_SECRET=${RAZORPAY_KEY_SECRET}
      - RAZORPAY_WEBHOOK_SECRET=${RAZORPAY_WEBHOOK_SECRET}

      - RABBITMQ_URL=amqp://rabbitmq:5672

      - INTERNAL_SECRET=${INTERNAL_SECRET}

      - INVOICE_SERVICE_URL=http://invoice-service:3003

    depends_on:
      - rabbitmq

    networks:
      - invoicehive_net


  notification-service:
    build: ./notification-service
    environment:
      - PORT=3005

      - RABBITMQ_URL=amqp://rabbitmq:5672

      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}

    depends_on:
      - rabbitmq

    networks:
      - invoicehive_net


  rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - "15672:15672"
    networks:
      - invoicehive_net


  minio:
    image: minio/minio
    command: server /data --console-address ":9001"

    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin

    ports:
      - "9000:9000"
      - "9001:9001"

    networks:
      - invoicehive_net


networks:
  invoicehive_net:
    driver: bridge