version: "3.9"

services:
  auth-service:
    build: .
    ports:
      - "3001:3001"

    environment:
      - NODE_ENV=development
      - PORT=3001

      # use MongoDB Atlas
      - MONGO_URI=${MONGO_URI}

      # use local docker redis
      - REDIS_URL=redis://redis:6379

      - JWT_ACCESS_SECRET=dev_access_secret_change_in_prod
      - JWT_REFRESH_SECRET=dev_refresh_secret_change_in_prod
      - JWT_ACCESS_EXPIRES_IN=15m
      - JWT_REFRESH_EXPIRES_IN=7d

      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_CALLBACK_URL=http://localhost:3001/auth/oauth/google/callback

      - GITHUB_CLIENT_ID=${HUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${HUB_CLIENT_SECRET}
      - GITHUB_CALLBACK_URL=http://localhost:3001/auth/oauth/github/callback

      - CLIENT_URL=http://localhost:3000

      - SMTP_HOST=${SMTP_HOST:-smtp.gmail.com}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}

      - EMAIL_FROM=InvoiceHive <noreply@invoicehive.io>

      - COOKIE_SECRET=dev_cookie_secret_change_in_prod

    volumes:
      - .:/app
      - /app/node_modules

    command: node --watch src/index.js

    depends_on:
      redis:
        condition: service_healthy

    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

    command: redis-server --appendonly yes

    volumes:
      - redis_data:/data

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis_data: